dependencies:
  - name: redis
    version: "^17.11.3"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: redis.enabled
  - name: postgresql
    version: "^12.5.5"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: postgresql.enabled
